### ISSUE TITLE
need a CONTRIBUTING document

### ISSUE THREAD

**Issue by ifsheldon** [tkaitchuck/Rust4JavaDevelopers#4]
I think a `CONTRIBUTING.md` is needed to guide people how to participate in editing this book.

For instance, a section of `mdbook` helps to denote that it is a build dependency.  

I think it is also needed to point out how people can change the source. For example, I don't know whether it is appropriate to rebuild the project and then make a pull request, which will lead to many non-semantic changes. Say, I want to change a typo, but after rebuilding, many files, other than the semantically related html and markdown files, will be changed by `mdbook`.

**Comment by tkaitchuck** [comment]
Added https://github.com/tkaitchuck/Rust4JavaDevelopers/blob/master/Contributing.md
